#TEST

#:access_key_id: AKIAIH4BZW2Z3R7XMV4Q
#:secret_access_key: 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

#END TEST

#THIS IS GO CODE
#THIS FILE IS NOT CURRENTLY BEING USED BY S3.RB WHICH NEED REFACTORING TO USE THIS FILE.
development:
AWS_ACCESS_KEY_ID: AKIAIH4BZW2Z3R7XMV4Q
AWS_SECRET_ACCESS_KEY: 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
